# -*- coding: utf-8 -*-
"""Task 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y0e0kL8UGEjW-SLoLO__8i5IWjRWIeAk
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')
data = {
    'Date': pd.date_range(start='2024-01-01', periods=10),
    'Tweet': [
        "I love Tesla cars! So innovative.",
        "Tesla stock is falling again, not good.",
        "Neutral news from Tesla today.",
        "Elon Musk makes bold moves as always.",
        "I'm tired of Tesla updates.",
        "Tesla just launched something amazing!",
        "No big Tesla news today.",
        "Tesla makes me nervous as an investor.",
        "Tesla's new update is pretty cool!",
        "Why is Tesla always in the news?"
    ]
}

df = pd.DataFrame(data)
sia = SentimentIntensityAnalyzer()
df["Sentiment_Score"] = df["Tweet"].apply(lambda x: sia.polarity_scores(x)["compound"])

def classify(score):
    if score >= 0.05:
        return "Positive"
    elif score <= -0.05:
        return "Negative"
    else:
        return "Neutral"

df["Sentiment"] = df["Sentiment_Score"].apply(classify)
plt.figure(figsize=(8, 5))
sns.countplot(data=df, x="Sentiment", palette="Set2")
plt.title("Sentiment Distribution (Sample Tweets)")
plt.xlabel("Sentiment")
plt.ylabel("Tweet Count")
plt.grid(True)
plt.show()

all_text = " ".join(df["Tweet"])
wordcloud = WordCloud(width=800, height=400, background_color="white").generate(all_text)

plt.figure(figsize=(10, 6))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("Word Cloud of Sample Tweets")
plt.show()

df.set_index("Date", inplace=True)
df["Sentiment_Score"].resample("D").mean().plot(figsize=(10, 5), color="purple")
plt.title("Daily Sentiment Trend (Sample Tweets)")
plt.ylabel("Average Sentiment Score")
plt.grid(True)
plt.show()