# -*- coding: utf-8 -*-
"""Task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15RZJOmP7JW9WWWzoz58Fm9j206AtpP8o
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

data = {
    'Gender': np.random.choice(['Male', 'Female', 'Other'], size=500, p=[0.45, 0.45, 0.10]),
    'Age': np.random.normal(loc=35, scale=10, size=500).astype(int)  # Normal distribution of ages
}
df = pd.DataFrame(data)

gender_counts = df['Gender'].value_counts()

plt.figure(figsize=(8, 5))
plt.bar(gender_counts.index, gender_counts.values, color=['skyblue', 'lightcoral', 'purple'])
plt.title('Gender Distribution')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
plt.hist(df['Age'], bins=15, color='mediumseagreen', edgecolor='black')
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()